singlylist: interface
	javac SinglyLinkedList.java

doublylist: interface
	javac DoublyLinkedList.java

interface:
	javac LinkedListInterface.java

run: singlylist
	java SinglyLinkedList
	
clean:
	rm *.class
