optimized: interface
	javac OptimizedQuickUnion.java

quickfind: interface
	javac QuickFind.java

quickunion: interface
	javac QuickUnion.java

interface:
	javac UnionFindInterface.java

clean:
	rm *.class
